baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Yu's blogs"
theme = 'hugo-book'
enableGitInfo = true


[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'auto'

  # Configure the date format used on the pages
  # - In git information
  # - In blog posts
  BookDateFormat = 'January 2, 2006'
